sindresorhus/awesome-chatgpt

readme.md
=> Add Chat Bling

readme.md
Using Fetch API + streaming ChatGPT data!
=> Add streams article

readme.md
=> Add cz-git

readme.md
Simple Changes.
- Added plugin for Embarcadero RAD Studio (Delphi & C++ Builder)
- Added Client library for Delphi programming language.
=> Added Delphi Client Library & IDE plugin.

readme.md
=> Add WordGPT

readme.md
=> add Tenere

readme.md
=> Add AICommand

readme.md
=> Add AI Shader

readme.md
=> Add shellChatGPT

readme.md
=> Added `chatgpt-telegram-bot` by karfly

readme.md
=> Add Chatbox

readme.md
=> Add ChatKit

readme.md
✅✅ **By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-chatgpt/blob/main/contributing.md) twice and made sure my submission follows it.**
=> Add Short Circuit

readme.md
=> Add chatgpt-demo

readme.md
=> Add pdfGPT

readme.md
=> add Chat Chat

readme.md
=> Add Shell-Genie

readme.md
=> Add ChatBoost

readme.md
=> Add ShellGPT

readme.md
=> Add LearnGPT

readme.md
=> Add Developer Duck

readme.md
=> Add PandasAI

readme.md
=> Add Ask-Anything

readme.md
=> add hello history app

readme.md
=> Add Visual ChatGPT

readme.md
=> Add Scikit-LLM

readme.md
=> Add OpenChat

readme.md
=> Add ChatGPT-MD

readme.md
=>  Add ChatGPT to Markdown bookmarklet link

readme.md
=> Add gpt-code-ui

readme.md
A CLI that helps you organize and manage your files using AI.
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
=> Added AIFiles

readme.md
=> Add EasyChat AI

readme.md
Hi!
Adding my paid mac postgres client - [pgMagic](https://pgmagic.app). It uses gpt-3.5-turbo (and soon other models) to generate SQL and immediately execute based on your database schema.
Thanks!
=> Add pgMagic

readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
add Vercel AI SDK, an open source library for building AI-powered user interfaces.
=> add package Vercel AI SDK

readme.md
=> Add ChatGPT Infinity to Browser extensions, update ChatGPT Widescreen Mode description, update URL for chatgpt.js

readme.md
=> Add Chapyter

readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
<br>
I added them to this section because they since evolved into chatbots:
=> Add DuckDuckGPT/BraveGPT to Bots

readme.md
=> Add ChatGPT Auto-Continue

readme.md
=> Add I Don't Care About Commit Message

readme.md
Add `openai-php/client` package
=> Add OpenAI PHP Client

readme.md
Add [Meeper.ai](https://github.com/pas1ko/meeper)
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
=> Add Meeper.ai

readme.md
=> Add Open interpreter

readme.md
=> Add Web3-GPT

readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Yes, I have double-checked everything. Thanks
=> Add SlidesAI

readme.md
=> Add CometLLM

readme.md
=> Add OpenAgents

readme.md
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
Add OpenAI Ruby client
=> Add OpenAI Ruby client

readme.md
=> Add YouTube Summary by TubeSum

readme.md
=> Add Wielded.com

readme.md
=> Add 16x Prompt

readme.md
=> Add AI Chat

readme.md
Add llm-ui a library for creating streaming UIs for LLM responses
=> Add llm-ui

readme.md
I developed this app using SwiftUI. It allows you to select a specific area of the screen, enter a prompt, and receive an answer. You can then chat about the captured image.
The base app is free and there is a pro upgrade for $14 with some extra features.
✅✅ I have read the contribution guidelines twice and hopefully haven't missed anything 🤞
=> Add ScreenSnapAI

readme.md
Added Smart Exceptions project
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
=> Add Smart Exceptions

readme.md
=> Add SwiftStyle AI

readme.md
=> Add QChatGPT

readme.md
Adds TextCraft under "Integrations".
⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆
=> Add TextCraft
